-- =============================================================================
-- INITIAL DATABASE SCHEMA
-- Solana Momentum Trading Bot
-- =============================================================================

-- Drop existing tables if they exist (for fresh setup)
DROP TABLE IF EXISTS daily_stats CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS rpc_health CASCADE;
DROP TABLE IF EXISTS positions CASCADE;
DROP TABLE IF EXISTS trades CASCADE;
DROP TABLE IF EXISTS signals CASCADE;
DROP TABLE IF EXISTS safety_checks CASCADE;
DROP TABLE IF EXISTS token_metrics CASCADE;
DROP TABLE IF EXISTS tokens CASCADE;

-- =============================================================================
-- TOKENS TABLE
-- Tracks all discovered tokens
-- =============================================================================
CREATE TABLE tokens (
    id SERIAL PRIMARY KEY,
    mint_address VARCHAR(44) UNIQUE NOT NULL,
    name VARCHAR(100),
    symbol VARCHAR(20),
    decimals SMALLINT DEFAULT 9,
    bonding_curve_address VARCHAR(44),
    created_at TIMESTAMPTZ,
    discovered_at TIMESTAMPTZ DEFAULT NOW(),
    migrated_at TIMESTAMPTZ,
    migration_status VARCHAR(20) DEFAULT 'pending',
    metadata JSONB DEFAULT '{}',

    CONSTRAINT valid_migration_status CHECK (
        migration_status IN ('pending', 'migrating', 'migrated', 'failed')
    )
);

CREATE INDEX idx_tokens_mint ON tokens(mint_address);
CREATE INDEX idx_tokens_status ON tokens(migration_status);
CREATE INDEX idx_tokens_discovered ON tokens(discovered_at DESC);
CREATE INDEX idx_tokens_bonding ON tokens(bonding_curve_address) WHERE bonding_curve_address IS NOT NULL;

-- =============================================================================
-- TOKEN METRICS TABLE (Time Series)
-- Stores periodic snapshots of token metrics
-- =============================================================================
CREATE TABLE token_metrics (
    id BIGSERIAL,
    token_id INTEGER NOT NULL REFERENCES tokens(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    bonding_progress DECIMAL(5,2),
    market_cap_usd DECIMAL(18,2),
    volume_5m DECIMAL(18,2),
    volume_1h DECIMAL(18,2),
    holder_count INTEGER,
    holder_velocity DECIMAL(10,4),
    liquidity_usd DECIMAL(18,2),
    momentum_score DECIMAL(5,2),
    safety_score DECIMAL(5,2),

    PRIMARY KEY (id, timestamp)
) PARTITION BY RANGE (timestamp);

-- Create partitions for the current and next few months
-- In production, you'd automate partition creation
CREATE TABLE token_metrics_2026_01 PARTITION OF token_metrics
    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE token_metrics_2026_02 PARTITION OF token_metrics
    FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE token_metrics_2026_03 PARTITION OF token_metrics
    FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE token_metrics_default PARTITION OF token_metrics DEFAULT;

CREATE INDEX idx_metrics_token_time ON token_metrics(token_id, timestamp DESC);
CREATE INDEX idx_metrics_score ON token_metrics(momentum_score DESC) WHERE momentum_score >= 50;

-- =============================================================================
-- SAFETY CHECKS TABLE
-- Stores results of token safety analysis
-- =============================================================================
CREATE TABLE safety_checks (
    id SERIAL PRIMARY KEY,
    token_id INTEGER NOT NULL REFERENCES tokens(id) ON DELETE CASCADE,
    checked_at TIMESTAMPTZ DEFAULT NOW(),
    mint_authority_revoked BOOLEAN,
    freeze_authority_revoked BOOLEAN,
    lp_burned BOOLEAN,
    lp_locked_until TIMESTAMPTZ,
    top_10_holder_percent DECIMAL(5,2),
    creator_holding_percent DECIMAL(5,2),
    creator_previous_rugs INTEGER DEFAULT 0,
    risk_level VARCHAR(20),
    flags JSONB DEFAULT '[]',
    passed BOOLEAN NOT NULL,

    CONSTRAINT valid_risk_level CHECK (
        risk_level IN ('low', 'medium', 'high', 'critical')
    )
);

CREATE INDEX idx_safety_token ON safety_checks(token_id);
CREATE INDEX idx_safety_passed ON safety_checks(passed, checked_at DESC);
CREATE INDEX idx_safety_risk ON safety_checks(risk_level) WHERE risk_level IN ('high', 'critical');

-- =============================================================================
-- SIGNALS TABLE
-- Trading signals generated by momentum engine
-- =============================================================================
CREATE TABLE signals (
    id SERIAL PRIMARY KEY,
    token_id INTEGER NOT NULL REFERENCES tokens(id) ON DELETE CASCADE,
    signal_type VARCHAR(20) NOT NULL,
    momentum_score DECIMAL(5,2),
    confidence DECIMAL(3,2),
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    executed BOOLEAN DEFAULT FALSE,
    executed_at TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}',

    CONSTRAINT valid_signal_type CHECK (
        signal_type IN ('BUY', 'STRONG_BUY', 'SELL', 'STRONG_SELL', 'HOLD')
    )
);

CREATE INDEX idx_signals_token ON signals(token_id);
CREATE INDEX idx_signals_type ON signals(signal_type, created_at DESC);
CREATE INDEX idx_signals_unexecuted ON signals(executed, created_at DESC) WHERE executed = FALSE;

-- =============================================================================
-- TRADES TABLE
-- Executed trade records
-- =============================================================================
CREATE TABLE trades (
    id SERIAL PRIMARY KEY,
    token_id INTEGER NOT NULL REFERENCES tokens(id) ON DELETE CASCADE,
    signal_id INTEGER REFERENCES signals(id),
    trade_type VARCHAR(20) NOT NULL,
    side VARCHAR(10) NOT NULL,
    sol_amount DECIMAL(18,9),
    token_amount DECIMAL(24,9),
    price DECIMAL(24,12),
    slippage_bps INTEGER,
    priority_fee_lamports BIGINT,
    wallet_address VARCHAR(44),
    tx_signature VARCHAR(88),
    status VARCHAR(20) DEFAULT 'pending',
    error_message TEXT,
    executed_at TIMESTAMPTZ DEFAULT NOW(),
    confirmed_at TIMESTAMPTZ,
    pnl_sol DECIMAL(18,9),
    pnl_percent DECIMAL(8,4),

    CONSTRAINT valid_trade_type CHECK (
        trade_type IN ('entry', 'exit', 'stop_loss', 'take_profit', 'emergency')
    ),
    CONSTRAINT valid_side CHECK (side IN ('buy', 'sell')),
    CONSTRAINT valid_status CHECK (
        status IN ('pending', 'submitted', 'confirmed', 'failed', 'cancelled')
    )
);

CREATE INDEX idx_trades_token ON trades(token_id);
CREATE INDEX idx_trades_signature ON trades(tx_signature) WHERE tx_signature IS NOT NULL;
CREATE INDEX idx_trades_status ON trades(status, executed_at DESC);
CREATE INDEX idx_trades_wallet ON trades(wallet_address, executed_at DESC);

-- =============================================================================
-- POSITIONS TABLE
-- Open trading positions
-- =============================================================================
CREATE TABLE positions (
    id SERIAL PRIMARY KEY,
    token_id INTEGER NOT NULL REFERENCES tokens(id) ON DELETE CASCADE,
    status VARCHAR(20) DEFAULT 'open',
    entry_price DECIMAL(24,12),
    current_price DECIMAL(24,12),
    token_amount DECIMAL(24,9),
    cost_basis_sol DECIMAL(18,9),
    unrealized_pnl_sol DECIMAL(18,9),
    unrealized_pnl_percent DECIMAL(8,4),
    stop_loss_price DECIMAL(24,12),
    take_profit_levels JSONB DEFAULT '[]',
    opened_at TIMESTAMPTZ DEFAULT NOW(),
    closed_at TIMESTAMPTZ,
    close_reason VARCHAR(50),

    CONSTRAINT valid_position_status CHECK (
        status IN ('open', 'partial_close', 'closed')
    ),
    CONSTRAINT valid_close_reason CHECK (
        close_reason IS NULL OR close_reason IN (
            'take_profit', 'stop_loss', 'manual', 'kill_switch', 'risk_limit', 'migration_exit'
        )
    )
);

CREATE INDEX idx_positions_status ON positions(status);
CREATE INDEX idx_positions_token ON positions(token_id) WHERE status = 'open';
CREATE INDEX idx_positions_opened ON positions(opened_at DESC);

-- =============================================================================
-- RPC HEALTH TABLE
-- Tracks RPC endpoint health over time
-- =============================================================================
CREATE TABLE rpc_health (
    id SERIAL PRIMARY KEY,
    endpoint VARCHAR(255) NOT NULL,
    checked_at TIMESTAMPTZ DEFAULT NOW(),
    latency_ms INTEGER,
    is_healthy BOOLEAN,
    error_message TEXT,
    slot_behind INTEGER
);

CREATE INDEX idx_rpc_health_endpoint ON rpc_health(endpoint, checked_at DESC);
CREATE INDEX idx_rpc_health_unhealthy ON rpc_health(is_healthy, checked_at DESC) WHERE is_healthy = FALSE;

-- Retention: Keep only last 7 days of health checks
-- (Would be handled by a scheduled job in production)

-- =============================================================================
-- ALERTS TABLE
-- Notifications sent by the bot
-- =============================================================================
CREATE TABLE alerts (
    id SERIAL PRIMARY KEY,
    alert_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    message TEXT NOT NULL,
    data JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    sent_at TIMESTAMPTZ,
    acknowledged_at TIMESTAMPTZ,

    CONSTRAINT valid_severity CHECK (
        severity IN ('info', 'warning', 'error', 'critical')
    )
);

CREATE INDEX idx_alerts_type ON alerts(alert_type, created_at DESC);
CREATE INDEX idx_alerts_severity ON alerts(severity, created_at DESC);
CREATE INDEX idx_alerts_unacked ON alerts(acknowledged_at) WHERE acknowledged_at IS NULL;

-- =============================================================================
-- DAILY STATS TABLE
-- Aggregated daily statistics
-- =============================================================================
CREATE TABLE daily_stats (
    date DATE PRIMARY KEY,
    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    total_pnl_sol DECIMAL(18,9) DEFAULT 0,
    max_drawdown_percent DECIMAL(8,4),
    tokens_analyzed INTEGER DEFAULT 0,
    signals_generated INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_daily_stats_date ON daily_stats(date DESC);

-- =============================================================================
-- USEFUL VIEWS
-- =============================================================================

-- Active tokens with latest metrics
CREATE OR REPLACE VIEW v_active_tokens AS
SELECT
    t.*,
    m.bonding_progress,
    m.market_cap_usd,
    m.momentum_score,
    m.safety_score,
    m.holder_count,
    m.timestamp as metrics_updated_at
FROM tokens t
LEFT JOIN LATERAL (
    SELECT *
    FROM token_metrics
    WHERE token_id = t.id
    ORDER BY timestamp DESC
    LIMIT 1
) m ON true
WHERE t.migration_status = 'pending';

-- Open positions with current metrics
CREATE OR REPLACE VIEW v_open_positions AS
SELECT
    p.*,
    t.mint_address,
    t.symbol,
    t.name,
    m.market_cap_usd as current_market_cap,
    m.liquidity_usd as current_liquidity
FROM positions p
JOIN tokens t ON p.token_id = t.id
LEFT JOIN LATERAL (
    SELECT market_cap_usd, liquidity_usd
    FROM token_metrics
    WHERE token_id = t.id
    ORDER BY timestamp DESC
    LIMIT 1
) m ON true
WHERE p.status = 'open';

-- Today's trading summary
CREATE OR REPLACE VIEW v_today_summary AS
SELECT
    COUNT(*) as total_trades,
    COUNT(*) FILTER (WHERE pnl_sol > 0) as winning_trades,
    COUNT(*) FILTER (WHERE pnl_sol < 0) as losing_trades,
    COALESCE(SUM(pnl_sol), 0) as total_pnl_sol,
    COALESCE(AVG(pnl_percent), 0) as avg_pnl_percent
FROM trades
WHERE executed_at >= CURRENT_DATE
AND status = 'confirmed';

-- =============================================================================
-- FUNCTIONS
-- =============================================================================

-- Function to update daily stats
CREATE OR REPLACE FUNCTION update_daily_stats(target_date DATE DEFAULT CURRENT_DATE)
RETURNS void AS $$
BEGIN
    INSERT INTO daily_stats (date, total_trades, winning_trades, losing_trades, total_pnl_sol)
    SELECT
        target_date,
        COUNT(*),
        COUNT(*) FILTER (WHERE pnl_sol > 0),
        COUNT(*) FILTER (WHERE pnl_sol < 0),
        COALESCE(SUM(pnl_sol), 0)
    FROM trades
    WHERE DATE(executed_at) = target_date
    AND status = 'confirmed'
    ON CONFLICT (date)
    DO UPDATE SET
        total_trades = EXCLUDED.total_trades,
        winning_trades = EXCLUDED.winning_trades,
        losing_trades = EXCLUDED.losing_trades,
        total_pnl_sol = EXCLUDED.total_pnl_sol,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- COMMENTS
-- =============================================================================
COMMENT ON TABLE tokens IS 'Discovered tokens from Pump.fun and other sources';
COMMENT ON TABLE token_metrics IS 'Time-series metrics for tokens (partitioned by month)';
COMMENT ON TABLE safety_checks IS 'Results of rug detection safety analysis';
COMMENT ON TABLE signals IS 'Trading signals generated by momentum engine';
COMMENT ON TABLE trades IS 'Executed trade records';
COMMENT ON TABLE positions IS 'Open and closed trading positions';
COMMENT ON TABLE rpc_health IS 'RPC endpoint health monitoring';
COMMENT ON TABLE alerts IS 'Notifications and alerts sent by the bot';
COMMENT ON TABLE daily_stats IS 'Aggregated daily trading statistics';
