/**
 * Core TypeScript Types and Interfaces
 *
 * Defines the fundamental data structures used throughout the bot.
 */

import { Decimal } from 'decimal.js';

// =============================================================================
// BASIC TYPES
// =============================================================================

/** Solana address as string (44 characters) */
export type SolanaAddress = string;

/** Transaction signature (88 characters) */
export type TransactionSignature = string;

/** Unix timestamp in milliseconds */
export type Timestamp = number;

/** Price in USD or SOL */
export type Price = Decimal;

/** Amount in base units (lamports or token base units) */
export type Amount = bigint;

// =============================================================================
// TOKEN TYPES
// =============================================================================

/**
 * Token metadata and state
 */
export interface Token {
  /** Database ID */
  id?: number;

  /** Token mint address */
  mintAddress: SolanaAddress;

  /** Token name */
  name: string | null;

  /** Token symbol */
  symbol: string | null;

  /** Token decimals */
  decimals: number;

  /** Pump.fun bonding curve address */
  bondingCurveAddress: SolanaAddress | null;

  /** When the token was created on-chain */
  createdAt: Date | null;

  /** When we discovered the token */
  discoveredAt: Date;

  /** When the token migrated to Raydium */
  migratedAt: Date | null;

  /** Current migration status */
  migrationStatus: MigrationStatus;

  /** Additional metadata (JSON) */
  metadata: Record<string, unknown>;
}

export type MigrationStatus = 'pending' | 'migrating' | 'migrated' | 'failed';

// =============================================================================
// METRICS TYPES
// =============================================================================

/**
 * Token metrics snapshot (time-series data)
 */
export interface TokenMetrics {
  /** Database ID */
  id?: number;

  /** Token database ID */
  tokenId: number;

  /** Snapshot timestamp */
  timestamp: Date;

  /** Bonding curve progress (0-100%) */
  bondingProgress: number;

  /** Market cap in USD */
  marketCapUsd: Decimal;

  /** Volume in last 5 minutes (USD) */
  volume5m: Decimal;

  /** Volume in last 1 hour (USD) */
  volume1h: Decimal;

  /** Number of holders */
  holderCount: number;

  /** Holder velocity (new holders per minute) */
  holderVelocity: number;

  /** Liquidity depth in USD */
  liquidityUsd: Decimal;

  /** Calculated momentum score (0-100) */
  momentumScore: number;

  /** Calculated safety score (0-100) */
  safetyScore: number;
}

// =============================================================================
// SAFETY TYPES
// =============================================================================

/**
 * Result of safety analysis for a token
 */
export interface SafetyCheck {
  /** Database ID */
  id?: number;

  /** Token database ID */
  tokenId: number;

  /** When the check was performed */
  checkedAt: Date;

  /** Whether mint authority is revoked */
  mintAuthorityRevoked: boolean;

  /** Whether freeze authority is revoked */
  freezeAuthorityRevoked: boolean;

  /** Whether LP tokens are burned */
  lpBurned: boolean;

  /** LP lock expiry date (if locked but not burned) */
  lpLockedUntil: Date | null;

  /** Top 10 holder concentration percentage */
  top10HolderPercent: number;

  /** Creator wallet holding percentage */
  creatorHoldingPercent: number;

  /** Number of previous rugs by creator */
  creatorPreviousRugs: number;

  /** Overall risk level */
  riskLevel: RiskLevel;

  /** Specific flags raised */
  flags: SafetyFlag[];

  /** Whether the token passed safety checks */
  passed: boolean;
}

export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';

export type SafetyFlag =
  | 'mint_authority_active'
  | 'freeze_authority_active'
  | 'lp_unlocked'
  | 'high_holder_concentration'
  | 'creator_is_known_rugger'
  | 'low_liquidity'
  | 'honeypot_suspected'
  | 'wash_trading_suspected';

// =============================================================================
// SIGNAL TYPES
// =============================================================================

/**
 * Trading signal generated by the momentum engine
 */
export interface Signal {
  /** Database ID */
  id?: number;

  /** Token database ID */
  tokenId: number;

  /** Signal type */
  signalType: SignalType;

  /** Momentum score at signal time */
  momentumScore: number;

  /** Confidence level (0-1) */
  confidence: number;

  /** Reason for the signal */
  reason: string;

  /** When the signal was generated */
  createdAt: Date;

  /** Whether the signal was executed */
  executed: boolean;

  /** When the signal was executed */
  executedAt: Date | null;

  /** Additional metadata */
  metadata: Record<string, unknown>;
}

export type SignalType = 'BUY' | 'STRONG_BUY' | 'SELL' | 'STRONG_SELL' | 'HOLD';

// =============================================================================
// TRADE TYPES
// =============================================================================

/**
 * Executed trade record
 */
export interface Trade {
  /** Database ID */
  id?: number;

  /** Token database ID */
  tokenId: number;

  /** Signal that triggered this trade */
  signalId: number | null;

  /** Trade type (entry or exit) */
  tradeType: TradeType;

  /** Trade side */
  side: TradeSide;

  /** SOL amount */
  solAmount: Decimal;

  /** Token amount */
  tokenAmount: Decimal;

  /** Execution price */
  price: Decimal;

  /** Slippage in basis points */
  slippageBps: number;

  /** Priority fee in lamports */
  priorityFeeLamports: bigint;

  /** Wallet address used */
  walletAddress: SolanaAddress;

  /** Transaction signature */
  txSignature: TransactionSignature | null;

  /** Trade status */
  status: TradeStatus;

  /** Error message if failed */
  errorMessage: string | null;

  /** When the trade was executed */
  executedAt: Date;

  /** When the trade was confirmed */
  confirmedAt: Date | null;

  /** P&L in SOL (for exit trades) */
  pnlSol: Decimal | null;

  /** P&L percentage (for exit trades) */
  pnlPercent: number | null;
}

export type TradeType = 'entry' | 'exit' | 'stop_loss' | 'take_profit' | 'emergency';
export type TradeSide = 'buy' | 'sell';
export type TradeStatus = 'pending' | 'submitted' | 'confirmed' | 'failed' | 'cancelled';

// =============================================================================
// POSITION TYPES
// =============================================================================

/**
 * Open trading position
 */
export interface Position {
  /** Database ID */
  id?: number;

  /** Token database ID */
  tokenId: number;

  /** Position status */
  status: PositionStatus;

  /** Entry price */
  entryPrice: Decimal;

  /** Current price */
  currentPrice: Decimal;

  /** Token amount held */
  tokenAmount: Decimal;

  /** Cost basis in SOL */
  costBasisSol: Decimal;

  /** Unrealized P&L in SOL */
  unrealizedPnlSol: Decimal;

  /** Unrealized P&L percentage */
  unrealizedPnlPercent: number;

  /** Stop-loss price */
  stopLossPrice: Decimal | null;

  /** Take-profit levels */
  takeProfitLevels: TakeProfitLevel[];

  /** When the position was opened */
  openedAt: Date;

  /** When the position was closed */
  closedAt: Date | null;

  /** Reason for closing */
  closeReason: CloseReason | null;
}

export type PositionStatus = 'open' | 'partial_close' | 'closed';
export type CloseReason =
  | 'take_profit'
  | 'stop_loss'
  | 'manual'
  | 'kill_switch'
  | 'risk_limit'
  | 'migration_exit';

/**
 * Take-profit level configuration
 */
export interface TakeProfitLevel {
  /** Price level (percentage above entry) */
  pricePercent: number;

  /** Percentage of position to sell */
  sellPercent: number;

  /** Whether this level has been triggered */
  triggered: boolean;
}

// =============================================================================
// RPC HEALTH TYPES
// =============================================================================

/**
 * RPC endpoint health status
 */
export interface RPCHealth {
  /** Database ID */
  id?: number;

  /** Endpoint URL */
  endpoint: string;

  /** When the check was performed */
  checkedAt: Date;

  /** Response latency in milliseconds */
  latencyMs: number;

  /** Whether the endpoint is healthy */
  isHealthy: boolean;

  /** Error message if unhealthy */
  errorMessage: string | null;

  /** How many slots behind the endpoint is */
  slotBehind: number;
}

// =============================================================================
// ALERT TYPES
// =============================================================================

/**
 * Alert/notification record
 */
export interface Alert {
  /** Database ID */
  id?: number;

  /** Alert type */
  alertType: AlertType;

  /** Severity level */
  severity: AlertSeverity;

  /** Alert message */
  message: string;

  /** Additional data */
  data: Record<string, unknown>;

  /** When the alert was created */
  createdAt: Date;

  /** When the alert was sent */
  sentAt: Date | null;

  /** When the alert was acknowledged */
  acknowledgedAt: Date | null;
}

export type AlertType =
  | 'trade_executed'
  | 'trade_failed'
  | 'position_opened'
  | 'position_closed'
  | 'stop_loss_triggered'
  | 'take_profit_triggered'
  | 'kill_switch_activated'
  | 'risk_limit_exceeded'
  | 'rpc_unhealthy'
  | 'database_error'
  | 'system_error';

export type AlertSeverity = 'info' | 'warning' | 'error' | 'critical';

// =============================================================================
// DAILY STATS TYPES
// =============================================================================

/**
 * Daily statistics rollup
 */
export interface DailyStats {
  /** Date (primary key) */
  date: Date;

  /** Total number of trades */
  totalTrades: number;

  /** Number of winning trades */
  winningTrades: number;

  /** Number of losing trades */
  losingTrades: number;

  /** Total P&L in SOL */
  totalPnlSol: Decimal;

  /** Maximum drawdown percentage */
  maxDrawdownPercent: number;

  /** Tokens analyzed */
  tokensAnalyzed: number;

  /** Signals generated */
  signalsGenerated: number;
}

// =============================================================================
// BOT STATE TYPES
// =============================================================================

/**
 * Overall bot status
 */
export type BotStatus = 'starting' | 'running' | 'paused' | 'stopping' | 'stopped' | 'error';

/**
 * Kill switch state
 */
export interface KillSwitchState {
  /** Whether the kill switch is active */
  active: boolean;

  /** Reason for activation */
  reason: string | null;

  /** Who/what triggered it */
  triggeredBy: string | null;

  /** When it was triggered */
  triggeredAt: Date | null;
}

/**
 * Risk manager state
 */
export interface RiskState {
  /** Current total exposure in SOL */
  currentExposureSol: Decimal;

  /** Number of open positions */
  openPositions: number;

  /** Today's P&L in SOL */
  dailyPnlSol: Decimal;

  /** Today's P&L percentage */
  dailyPnlPercent: number;

  /** Peak capital (for drawdown calculation) */
  peakCapitalSol: Decimal;

  /** Current capital */
  currentCapitalSol: Decimal;

  /** Current drawdown percentage */
  currentDrawdownPercent: number;

  /** Whether trading is enabled */
  tradingEnabled: boolean;
}

// =============================================================================
// JUPITER TYPES
// =============================================================================

/**
 * Jupiter quote response
 */
export interface JupiterQuote {
  inputMint: string;
  outputMint: string;
  inAmount: string;
  outAmount: string;
  otherAmountThreshold: string;
  priceImpactPct: string;
  slippageBps: number;
  routePlan: JupiterRoutePlan[];
}

export interface JupiterRoutePlan {
  swapInfo: {
    ammKey: string;
    label: string;
    inputMint: string;
    outputMint: string;
    inAmount: string;
    outAmount: string;
    feeAmount: string;
    feeMint: string;
  };
  percent: number;
}

// =============================================================================
// EVENT TYPES
// =============================================================================

/**
 * Generic event emitted by the bot
 */
export interface BotEvent<T = unknown> {
  type: string;
  timestamp: Date;
  data: T;
}

/**
 * Token discovered event
 */
export interface TokenDiscoveredEvent {
  token: Token;
  source: 'grpc' | 'poll' | 'manual';
}

/**
 * Metrics updated event
 */
export interface MetricsUpdatedEvent {
  tokenId: number;
  metrics: TokenMetrics;
}

/**
 * Signal generated event
 */
export interface SignalGeneratedEvent {
  signal: Signal;
  token: Token;
}

/**
 * Trade executed event
 */
export interface TradeExecutedEvent {
  trade: Trade;
  position: Position | null;
}
